---
name: "Unit Test"
permissions:
  contents: read
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: "1.26.x"
          check-latest: true
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Test
        run: make test
        env:
          ENVTEST_K8S_VERSION: 1.34.1
      - name: Lint
        run: make lint
